spring:
  application:
    name: cart-qry

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    org.springframework.data.couchbase.repository.query: DEBUG